server:
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/soccer-club-db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  security:
    user:
      name: "Test User"
      password: "123456"