server:
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/soccer-club-db?createDatabaseIfNotExist=true
    username: root
    password: Ninjahaupt1

#  security:
#    user:
#      name: "Test User"
#      password: "123456"
